// Portfolio/src/App/Stack/Stack.jsx
import styles from './Stack.module.css';

import PythonModal from './TechModals/PythonModal';
import CSharpModal from './TechModals/CSharpModal';
import JSModal from './TechModals/JSModal';
import AzFuncModal from './TechModals/AzFuncModal';
import SQLModal from './TechModals/SQLModal';
import HtmlModal from './TechModals/HtmlModal';
import GitModal from './TechModals/GitModal';
import CSSModal from './TechModals/CSSModal';
import JavaModal from './TechModals/JavaModal';
import RustModal from './TechModals/RustModal';

import cssLogo from '../../assets/logos/css-logo.png';
import javaLogo from '../../assets/logos/java-logo.png';
import pyLogo from '../../assets/logos/py-logo.png';
import htmlLogo from '../../assets/logos/html-logo.png';
import jsLogo from '../../assets/logos/js-logo.png';
import csLogo from '../../assets/logos/cs-logo.png';
import gitLogo from '../../assets/logos/git-logo.png';
import sqlLogo from '../../assets/logos/sql-logo.png';
import rustLogo from '../../assets/logos/rust-logo.png';
import azFuncLogo from '../../assets/logos/az-func-logo.png';

import { useState, useEffect } from 'react';

export default function Stack({ stackRef }) {

    const [scrolledBy, setScrolledBy] = useState(false);
    const [modalVisible, setModalVisible] = useState(null);
    const [showStackItems, setShowStackItems] = useState(true);

    const modals = [
        {
            name: 'css',
            title: 'CSS',
            img: cssLogo,
            fadeInStyle: 'fadeInNW',
            fadeOutStyle: showStackItems ? 'fadeOutSE' : 'fadeGone',
            modal: <CSSModal />,
            color: 'blue',
            col: 0
        },
        {
            name: 'java',
            title: 'Java',
            img: javaLogo,
            fadeInStyle: 'fadeInW',
            fadeOutStyle: showStackItems ? 'fadeOutE' : 'fadeGone',
            modal: <JavaModal />,
            color: 'red',
            col: 0
        },
        {
            name: 'python',
            title: 'Python',
            img: pyLogo,
            fadeInStyle: 'fadeInSW',
            fadeOutStyle: showStackItems ? 'fadeOutNE' : 'fadeGone',
            modal: <PythonModal setModalVisible={setModalVisible} />,
            color: 'blue',
            col: 0
        },
        {
            name: 'html',
            title: 'HTML',
            img: htmlLogo,
            fadeInStyle: 'fadeInN',
            fadeOutStyle: showStackItems ? 'fadeOutS' : 'fadeGone',
            modal: <HtmlModal />,
            color: 'orange',
            col: 1
        },
        {
            name: 'js',
            title: 'JavaScript',
            img: jsLogo,
            fadeInStyle: 'fadeIn',
            fadeOutStyle: showStackItems ? 'fadeOut' : 'fadeGone',
            modal: <JSModal />,
            color: 'yellow',
            col: 1
        },
        {
            name: 'csharp',
            title: 'C#',
            img: csLogo,
            fadeInStyle: 'fadeIn',
            fadeOutStyle: showStackItems ? 'fadeOut' : 'fadeGone',
            modal: <CSharpModal />,
            color: 'purple',
            col: 1
        },
        {
            name: 'git',
            title: 'Git',
            img: gitLogo,
            fadeInStyle: 'fadeInS',
            fadeOutStyle: showStackItems ? 'fadeOutN' : 'fadeGone',
            modal: <GitModal />,
            color: 'orange',
            col: 1
        },
        {
            name: 'sql',
            title: 'SQL',
            img: sqlLogo,
            fadeInStyle: 'fadeInNE',
            fadeOutStyle: showStackItems ? 'fadeOutSW' : 'fadeGone',
            modal: <SQLModal />,
            color: 'blue',
            col: 2
        },
        {
            name: 'rust',
            title: 'Rust',
            img: rustLogo,
            fadeInStyle: 'fadeInE',
            fadeOutStyle: showStackItems ? 'fadeOutW' : 'fadeGone',
            modal: <RustModal />,
            color: 'orange',
            col: 2
        },
        {
            name: 'azFunc',
            title: 'Azure Functions',
            img: azFuncLogo,
            fadeInStyle: 'fadeInSE',
            fadeOutStyle: showStackItems ? 'fadeOutNW' : 'fadeGone',
            modal: <AzFuncModal setModalVisible={setModalVisible} />,
            color: 'blue',
            col: 2
        }
    ];

    const itemClick = (name) => {
        setModalVisible(name);
        setTimeout(() => {
            setShowStackItems(false);
        }, 1000);
    }

    const closeModal = () => {
        setModalVisible(null);
        setShowStackItems(true);
    }

    const scrollView = () => {
        const observer = new IntersectionObserver(
            ([entry]) => {
                if (entry.isIntersecting) {
                    setScrolledBy(true);
                    observer.disconnect(); // Stop observing after first intersection
                }
            },
            {
                threshold: 0.2, // Trigger when 20% of the element is visible
            }
        );

        if (stackRef.current) {
            observer.observe(stackRef.current);
        }

        return () => {
            if (stackRef.current) {
                observer.unobserve(stackRef.current);
            }
        };
    }

    useEffect(() => {
        window.addEventListener('scroll', scrollView);

        return () => {
            window.removeEventListener('scroll', scrollView);
        };
    }, []);
    return (
        <div className={styles.stackPage} ref={stackRef}>
            <h1>My Tech Stack</h1>
            <div className={styles.stackContainer}>
                {Array.from({ length: 3 }).map((_, index) => (
                    <StackColumn key={index} modals={modals.filter(modal => modal.col === index)} setModalVisible={itemClick} scrolledBy={scrolledBy} modalVisible={modalVisible}/>
                ))}
            </div>
            {modals.map((modal) => (
                (modalVisible === modal.name) && (
                    <TechModal key={modal.name} closeModal={closeModal} color={`var(--${modal.color}-color)`} modalContent={modal.modal} />
                )
            ))}
        </div>
    );
}

function StackColumn({ modals, setModalVisible, scrolledBy, modalVisible }) {
    return (
        <div className={styles.stackColumn}>
            {modals.map((modal) => (
                <StackItem
                    key={modal.name}
                    scrollByClass={(modalVisible!==null) ? modal.fadeOutStyle : scrolledBy ? modal.fadeInStyle : ''}
                    image={modal.img}
                    text={modal.title}
                    onclick={() => setModalVisible(modal.name)}
                    color={modal.color}
                />
            ))}
        </div>
    );
}

function StackItem({ image, text, scrollByClass, onclick = () => {}, color='black'}) {
    // if hoverEffect is not true add stackItem class to div
    let btnClassName = `${styles.stackItem} ${styles[`${color}`]}`;
    if (scrollByClass) {
        btnClassName += ` ${scrollByClass}`;
    }
    return (
        <button className={btnClassName} onClick={onclick}>
            <img draggable={false} src={image} alt={text} />
            <h3>{text}</h3>
        </button>
    );
}

function TechModal({ closeModal, modalContent, color }) {
    return (
        <>
            <div className={`${styles.modal} fadeInModal`} style={{ borderColor: color, boxShadow: `0px 0px 20px ${color}` }}>
                {modalContent}
                <button className={styles.closeButton} onClick={closeModal}>X</button>
            </div>
            <div className={styles.modalBackdrop} onClick={closeModal}></div>
        </>
    );
}

// svel-portfolio/src/App/Pages/Stack/Stack.svelte
<script lang="ts">

    import { onMount } from 'svelte';

    import { pageRefs } from '../../../Stores/pageRefs.svelte'

    import type { ModalFadeStates, StackItemFadeStates, Modal } from '../../../Types/tech-stack';

    import TechStack from './TechStack/TechStack.svelte';
    import TechModal from './TechModals/TechModal.svelte';
    import StackDesc from './StackDesc.svelte';

    import javaLogo from '../../../assets/logos/java-logo.png';
    import JavaModal from './TechModals/JavaModal.svelte';
    import pyLogo from '../../../assets/logos/py-logo.png';
    import PythonModal from './TechModals/PythonModal.svelte';
    import htmlCSSLogo from '../../../assets/logos/html-css-logo.png';
    import HtmlModal from './TechModals/HtmlModal.svelte';
    import jsLogo from '../../../assets/logos/js-logo.png';
    import JSModal from './TechModals/JavaScriptModal.svelte';
    import csLogo from '../../../assets/logos/cs-logo.png';
    import CSharpModal from './TechModals/CSharpModal.svelte';
    import sqlLogo from '../../../assets/logos/sql-logo.png';
    import SQLModal from './TechModals/SQLModal.svelte';
    import rustLogo from '../../../assets/logos/rust-logo.png';
    import RustModal from './TechModals/RustModal.svelte';
    import azFuncLogo from '../../../assets/logos/az-func-logo.png';
    import AzFuncModal from './TechModals/AzFuncModal.svelte';

    type Props = {
        scrollToSection: (sectionRef: HTMLDivElement | null, moreOffset?: boolean) => void;
    }

    let { scrollToSection }: Props = $props();

    let modalVisible = $state<Modal | null>(null);
    let modalFadeState = $state<ModalFadeStates>('fadeInModal');
    let stackItemFadeState = $state<StackItemFadeStates>('fadeIn');
    let spinAnimation = $state<boolean>(false);

    const openModal = (modalName: string) => {
        const modal = modals.find(m => m.name === modalName);
        if (modal) {
            let timeout = 0;
            if (modalVisible) {
                modalFadeState = 'fadeOutModal';
                timeout = 1000;
            }
            setTimeout(() => {
                if (timeout) modalVisible = modal;
                modalFadeState = 'fadeInModal';
                stackItemFadeState = 'fadeOut';
                setTimeout(() => {
                    spinAnimation = false;
                    modalVisible = modal;
                }, 1000);
            }, timeout);
        }
    }

    const closeModal = () => {
        modalFadeState = 'fadeOutModal';
        setTimeout(() => {
            modalVisible = null;
            modalFadeState = undefined;
            spinAnimation = true;
            stackItemFadeState = 'fadeIn';
        }, 1000);
    }

    const scrollToProject = (ref: HTMLDivElement | null) => {
        modalVisible = null;
        modalFadeState = undefined;
        stackItemFadeState = 'fadeIn';
        spinAnimation = true;
        scrollToSection(ref, true);
    }

    const modals: Modal[] = $derived([
        {
            name: 'java',
            title: 'Java',
            img: javaLogo,
            fadeDir: 'E',
            color: 'red',
            modal: JavaModal,
        },
        {
            name: 'python',
            title: 'Python',
            img: pyLogo,
            fadeDir: 'SE',
            color: 'blue',
            modal: PythonModal,
            props: {
                setModalVisible: openModal,
                scrollToProject,
            }
        },
        {
            name: 'html_css',
            title: 'HTML/CSS',
            img: htmlCSSLogo,
            fadeDir: 'S',
            color: 'blue',
            modal: HtmlModal
        },
        {
            name: 'js',
            title: 'JavaScript',
            img: jsLogo,
            fadeDir: 'SW',
            color: 'yellow',
            modal: JSModal, 
            props: {
                scrollToProject,
            }
            
        },
        {
            name: 'csharp',
            title: 'C#',
            img: csLogo,
            fadeDir: 'W',
            color: 'purple',
            modal: CSharpModal,
            props: {
                setModalVisible: openModal, 
                scrollToProject,
            }
        },
        {
            name: 'sql',
            title: 'SQL',
            img: sqlLogo,
            fadeDir: 'NW',
            color: 'blue',
            modal: SQLModal,
        },
        {
            name: 'rust',
            title: 'Rust',
            img: rustLogo,
            fadeDir: 'N',
            color: 'orange',
            modal: RustModal,
            props: {
                scrollToProject,
            }
        },
        {
            name: 'azFunc',
            title: 'Azure',
            img: azFuncLogo,
            fadeDir: 'NE',
            color: 'blue',
            modal: AzFuncModal,
            props: {setModalVisible: openModal }
        }
    ]);

    onMount(() => {
        setTimeout(() => {
            spinAnimation = true;
        }, 1200);
    })

</script>

<div class='stackPage' bind:this={pageRefs.pages.stack}>
    {#if modalVisible === null}
        <StackDesc {stackItemFadeState}/>
        <TechStack 
            {spinAnimation} 
            {stackItemFadeState} 
            {openModal}
            {modals}
        />
    {:else}
        <TechModal 
            {closeModal} 
            content={modalVisible.modal} 
            props={modalVisible.props}
            color={modalVisible.color}
            modalFadeClass={modalFadeState}
        />
    {/if}
</div>

<style>
    .stackPage {
        width: 100%;
        height: 95vh;
        display: flex;
        flex-direction: column;
        position: relative;
        align-items: center;
        color: var(--text-color);
        gap: 1rem;
        --inner-radius: 215px;
        --item-size: 120px;
        --gap: 50px;
        --radius: calc(var(--inner-radius) + var(--item-size) / 2 + var(--gap));
        overflow: hidden;
    }

    @media (max-width: 768px) {
        .stackPage {
            height: 55vh;
            min-height: 475px;
            --inner-radius: 125px;
            --item-size: 50px;
            --gap: 20px;
        }
    }
</style>
