// Portfolio/src/App/Background/Background.jsx
import styles from './Background.module.css';
import { useEffect, useRef, forwardRef } from 'react';

export default function Background() {
    const squaresRef = useRef([]);
    const allSquares = useRef([]);

    const numSquares = 125;
    useEffect(() => {
        const isMobile = window.innerWidth <= 768;
        const backgroundPixels = document.getElementById('root').getBoundingClientRect().height * (isMobile ? 1.1 : 1.05);
        console.log('Background height:', backgroundPixels); 
        const totalSquares = numSquares * 3;

        // Initialize square data
        allSquares.current = Array.from({ length: totalSquares }, () => ({
            x: Math.random() * window.innerWidth,
            y: Math.random() * backgroundPixels,
            speed: (isMobile ? 0.15 : 0.12) + Math.random() * 0.05,
            angle: Math.random() * 2 * Math.PI,
        }));

        function animate() {
            for (let i = 0; i < allSquares.current.length; i++) {
                let s = allSquares.current[i];
                s.x += s.speed * Math.cos(s.angle);
                s.y += s.speed * Math.sin(s.angle);

                if (s.x > window.innerWidth) s.x = 0;
                else if (s.x < 0) s.x = window.innerWidth;

                if (s.y > backgroundPixels) s.y = window.innerHeight;
                else if (s.y < window.innerHeight) s.y = backgroundPixels;

                const el = squaresRef.current[i];
                if (el) {
                    el.setAttribute('x', s.x);
                    el.setAttribute('y', s.y);
                }
            }
            requestAnimationFrame(animate);
        }

        requestAnimationFrame(animate);
    }, []);

    const squares = [];
    let id = 0;
    for (let i = 0; i < numSquares; i++) {
        for (let color of ['blue', 'green', 'pink']) {
            const index = id; // Capture current id for ref assignment
            squares.push(
                <Square
                    key={id}
                    id={`square-${id}`}
                    color={color}
                    width={0.025 + i * 0.0015}
                    ref={(el) => (squaresRef.current[index] = el)}
                />
            );
            id++;
        }
    }

    return (
        <svg className={styles.bg} width="100%" height="100%">
            <g id="bg-layer">
                <rect
                    style={{
                        fill: "var(--bg-color)",
                        stroke: '#4d4d4d',
                        strokeWidth: 0.264583
                    }}
                    width="100%"
                    height="100%"
                    x="0"
                    y="0"
                />
                {squares}
            </g>
        </svg>
    );
}

const Square = forwardRef(function Square({ color, width, id }, ref) {
    return (
        <rect
            ref={ref}
            id={id}
            className={styles.square}
            style={{
                fill: `var(--app-${color})`,
                stroke: '#4d4d4d',
                strokeWidth: 0.264583
            }}
            width={`${width}rem`}
            height={`${width}rem`}
            x={0}
            y={window.innerHeight + 55}
        />
    );
});

// svel-portfolio/src/App/Background/Background.svelte
<script lang="ts">

    import { onMount } from 'svelte';
    import { isMobile } from '../utils';

    type SquareData = {
        x: number;
        y: number;
        speed: number;
        angle: number;
        size: number;
        color: string;
        sizeIncreasing: boolean;
    };
    let canvasRef: HTMLCanvasElement;

    
    onMount(() => {
        const NUM_SQUARES = isMobile? 150 : 175;
        const root = document.getElementById('app') as HTMLDivElement;
        const TOTAL_SQUARES = NUM_SQUARES * 3;
        const COLORS = ['blue', 'green', 'pink'];
        const WIDTH = window.innerWidth;
        const HEIGHT = root.getBoundingClientRect().height;
        canvasRef.width = WIDTH;
        canvasRef.height = HEIGHT;
        const xPadding = (isMobile ? 0.1 : 0.025) * window.innerWidth;
        const MIN_X = - xPadding;
        const MAX_X = WIDTH + xPadding;
        const MIN_Y = window.innerHeight;
        const MAX_Y = HEIGHT;

        const SIZE_MULTIPLIER = 0.0095;
        const MIN_SIZE = 1.25;
        const MAX_SIZE = MIN_SIZE + TOTAL_SQUARES * SIZE_MULTIPLIER;

        const squares: SquareData[] = Array.from({ length: TOTAL_SQUARES }, (_, i) => ({
            x: Math.random() * WIDTH,
            y: MIN_Y + Math.random() * (MAX_Y - MIN_Y),
            speed: (isMobile ? 0.15 : 0.12) + Math.random() * 0.1,
            angle: Math.random() * 2 * Math.PI,
            size: MIN_SIZE + i * SIZE_MULTIPLIER,
            sizeIncreasing: i % 2 === 0,
            color: COLORS[i % COLORS.length]
        }));

        function updateSquares() {
            for (const square of squares) {
                square.x += square.speed * Math.cos(square.angle) * square.size / 5;
                square.y += square.speed * Math.sin(square.angle) * square.size / 5;

                if (square.x > MAX_X) square.x = MIN_X;
                else if (square.x < MIN_X) square.x = MAX_X;

                if (square.y > MAX_Y) square.y = MIN_Y;
                else if (square.y < MIN_Y) square.y = MAX_Y;
                
                if (square.sizeIncreasing) {
                    square.size += SIZE_MULTIPLIER / 1.25;
                    if (square.size >= MAX_SIZE) {
                        square.size = MAX_SIZE;
                        square.sizeIncreasing = false;
                    }
                } else {
                    square.size -= SIZE_MULTIPLIER / 1.25;
                    if (square.size <= MIN_SIZE) {
                        square.size = MIN_SIZE;
                        square.sizeIncreasing = true;
                    }
                }
            }
        }

        function animate() {
            const ctx = canvasRef.getContext('2d');
            if (ctx) {
                // console.log('Animating squares');
                ctx.clearRect(0, 0, WIDTH, HEIGHT);

                updateSquares();
                // sort by size, smallest to largest
                const sortedSquares = [...squares].sort((a, b) => a.size - b.size);
                // display squares
                for (const square of sortedSquares) {
                    const computedColor = getComputedStyle(document.documentElement).getPropertyValue(`--app-${square.color}`).trim();
                    ctx.fillStyle = computedColor;
                    ctx.shadowColor = computedColor;
                    ctx.shadowBlur = 7.5;
                    ctx.fillRect(square.x, square.y, square.size, square.size);
                }
            }
            requestAnimationFrame(animate);
        }
        requestAnimationFrame(animate);
    });

</script>

<canvas bind:this={canvasRef}></canvas>

<style>
    canvas {
        position: absolute;
        inset: 0;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -2;
        pointer-events: none;
        background-color: var(--bg-color);
    }
</style>
